name = "StorageMirrorServer"
uuid = "c599abfa-5b8f-4a17-b52a-f0b922b74a92"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.2.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CodecZlib = "0.7"
Glob = "1.3"
HTTP = "0.8.14"
IterTools = "1.3"
ProgressMeter = "1"
Tar = "1.3"
ThreadPools = "1.1"
TranscodingStreams = "0.9.5"
julia = "1.4"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Suppressor", "Test"]
